trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'azure-conn'
  EnvironmentType: 'Test'
  ResourceGroupName: 'iqblbicep'
  deploymentDefaultLocation: 'southeastasia'

jobs:
- job:
  steps:

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: deploy/main.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deployToyManualsStorageAccount $(DeployToyManualsStorageAccount)